name: bio

channels:
  - conda-forge
  - bioconda

dependencies:
  - fastp==1.0.1
  - fastqc==0.11.9
  - hisat2==2.2.1
  - python==3.13.*
  - snakemake==9.13.2
  - samtools==1.22.1
  - freebayes==1.3.10
  - subread==2.1.1
